### ISSUE TITLE
Incorrect info on makers page and broken link in the printables page

### ISSUE THREAD

**Issue by MHache1717** [makersmakingchange/Rumble-Plate-Dice-Roller#1]
Our device page indicates it can be activated by pressing down on the cup. Unless I've missed something the current design doesn't support this function.

On the printables page there is a link to "see it in action". Link appears to be broken. Probably pre new website 

https://makersmakingchange.com/wp-content/uploads/2021/11/DSCN0147.mov

**Comment by jakemcivor** [comment]
I've updated the original website listing, removed the broken link from Printables, and created a separate issue to update the documentation for this device (e.g., User Guide, Design Rational, CAD Files).

The Rumble Plate Dice Roller can be activated by pushing down on the cup with the (optional) Vertical Push Base assembly. The Dice Roller is placed on/within the Push Base, which has a small hinge that pushes the button on the side when the Dice Roller is pushed down. We could use some additional images and a User Guide to make this clearer.

**Comment by MHache1717** [comment]
Thanks. Didn't see any reference to the vertical push base but see the files on printables. If I get time next week I'll print it off and send some pictures
